=== DavidelPrado/2021_LMGSI_DPL/ud04/EjercicioCasa/13.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT plantilla (tipos|fieldset)*>
<!ATTLIST plantilla
    xsi:noNameSpaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED>

<!ELEMENT tipos (fieldset)*>
<!ELEMENT fieldset (legend|tipo|contenido)*>
<!ELEMENT legend (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT contenido (opcion|fecha|tiempo)*>
<!ELEMENT opcion (#PCDATA)>
<!ELEMENT fecha EMPTY>
<!ATTLIST fecha
    dia (01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31) #REQUIRED
    mes (01|02|03|04|05|06|07|08|09|10|11|12) #REQUIRED
    aÃ±o (2020|2021) #REQUIRED>
<!ELEMENT tiempo EMPTY>
<!ATTLIST tiempo
    horas (01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24) #REQUIRED
    minutos (01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59) #REQUIRED
    segundos (01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59) #REQUIRED>

=== DavidelPrado/2021_LMGSI_DPL/ud04/EjercicioCasa/13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plantilla SYSTEM "13.dtd">
<plantilla 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema"
    xsi:noNameSpaceSchemaLocation="esquema.xsd">
    <tipos>
        <fieldset>
            <legend>Tipo texto</legend>
            <tipo>Text</tipo>
        </fieldset>
        <fieldset>
            <legend>Tipo radio</legend>
            <tipo>Radio</tipo>
            <contenido>
                <opcion>Radio1</opcion>
                <opcion>Radio2</opcion>
                <opcion>Radio3</opcion>
            </contenido>
        </fieldset>
        <fieldset>
            <legend>Tipo checkbox</legend>
            <tipo>Checkbox</tipo>
            <contenido>
                <opcion>Checkbox1</opcion>
                <opcion>Checkbox2</opcion>
                <opcion>Checkbox3</opcion>
            </contenido>
        </fieldset>
        <fieldset>
            <legend>Tipo correo electronico</legend>
            <tipo>Email</tipo>
        </fieldset>
        <fieldset>
            <legend>Tipo telefono</legend>
            <tipo>Tel</tipo>
        </fieldset>
        <fieldset>
            <legend>Tipo fecha</legend>
            <tipo>Date</tipo>
            <contenido>
                <fecha dia="02" mes="03" año="2021"/>
            </contenido>
        </fieldset>
        <fieldset>
            <legend>Tipo hora</legend>
            <tipo>Time</tipo>
            <contenido>
                <tiempo horas="17" minutos="42" segundos="01"/>
            </contenido>
        </fieldset>
        <fieldset>
            <legend>Tipo semana</legend>
            <tipo>Week</tipo>
        </fieldset>
        <fieldset>
            <legend>Tipo mes</legend>
            <tipo>Month</tipo>
        </fieldset>
        <fieldset>
            <legend>Tipo texto</legend>
            <tipo>Texto</tipo>
        </fieldset>
        <fieldset>
            <legend>Tipo rango</legend>
            <tipo>Range</tipo>
        </fieldset>
    </tipos>
    <fieldset>
        <legend>Listas</legend>
        <tipo>List</tipo>
        <contenido>
            <opcion>Valor1</opcion>
            <opcion>Valor2</opcion>
            <opcion>Valor3</opcion>
        </contenido>
        <tipo>ListaDefinida</tipo>
        <contenido>
            <opcion>Opcion1</opcion>
            <opcion>Opcion2</opcion>
            <opcion>Opcion3</opcion>
        </contenido>
    </fieldset>
    <fieldset>
        <legend>Area de texto</legend>
        <tipo>TextArea</tipo>
    </fieldset>
    <fieldset>
        <legend>Imagen</legend>
        <tipo>Image</tipo>
    </fieldset>
    <fieldset>
        <legend>Busqueda</legend>
        <tipo>Search</tipo>
    </fieldset>
    <fieldset>
        <legend>Url</legend>
        <tipo>Url</tipo>
    </fieldset>
    <fieldset>
        <legend>Contraseña</legend>
        <tipo>Password</tipo>
    </fieldset>
    <fieldset>
        <legend>Numero</legend>
        <tipo>Number</tipo>
    </fieldset>
    <fieldset>
        <legend>Fichero</legend>
        <tipo>File</tipo>
    </fieldset>
    <fieldset>
        <legend>Color</legend>
        <tipo>Color</tipo>
    </fieldset>
    <fieldset>
        <legend>Restablecer</legend>
        <tipo>Reset</tipo>
    </fieldset>
</plantilla>
