=== DavidelPrado/2021_LMGSI_DPL/examenes/Ex02_20210309_DaviddelPradoLosada/mapaestelar.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT mapaEstelar (constelacion+)>
<!ATTLIST mapaEstelar
    xsi:noNameSpaceSchemaLocation CDATA #IMPLIED
    xmlns:xsi CDATA #IMPLIED>
<!ELEMENT constelacion (nombreEspañol,superficie,estrellas,objetos,colindantes,observacion)>
<!ATTLIST constelacion
    nombreLatin CDATA #REQUIRED>

<!ELEMENT nombreEspañol (#PCDATA)>
<!ELEMENT superficie (#PCDATA)>
<!ELEMENT estrellas (asterismo,masbrillante)>
<!ATTLIST estrellas
    numeroEstrellas CDATA #REQUIRED>
<!ELEMENT asterismo (#PCDATA)>
<!ELEMENT masbrillante (#PCDATA)>
<!ATTLIST masbrillante
    luminosidad CDATA #REQUIRED>

<!ELEMENT objetos (cumulos,nebulosas,galaxias,cuasares,lluviaMeteoros*)>
<!ELEMENT cumulos (#PCDATA)>
<!ELEMENT nebulosas (#PCDATA)>
<!ELEMENT galaxias (#PCDATA)>
<!ELEMENT cuasares (#PCDATA)>
<!ELEMENT lluviaMeteoros (#PCDATA)>

<!ELEMENT colindantes (#PCDATA)>
<!ELEMENT observacion (hemisferio,mes,hora)>
<!ELEMENT hemisferio (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT hora (#PCDATA)>

=== DavidelPrado/2021_LMGSI_DPL/Ex02_20210309_DaviddelPradoLosada/mapaestelar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapaEstelar SYSTEM 'mapaestelar.dtd'>
<mapaEstelar
    xmlns:xsi="http://www.w3.org/2001/XMLSchema"
    xsi:noNameSpaceSchemaLocation="mapaestelar.xsd">
    <constelacion nombreLatin="Ursa Maior">
        <nombreEspañol>La Osa Mayor</nombreEspañol>
        <superficie>1279,7</superficie>
        <estrellas numeroEstrellas="209">
            <asterismo>7</asterismo>
            <masbrillante luminosidad="1,77">Alioth</masbrillante>
        </estrellas>
        <objetos>
            <cumulos>false</cumulos>
            <nebulosas>true</nebulosas>
            <galaxias>true</galaxias>
            <cuasares>false</cuasares>
            <lluviaMeteoros>Kappa Ursa Mayoridas</lluviaMeteoros>
            <lluviaMeteoros>Lambda Ursa Mayoridas</lluviaMeteoros>
            <lluviaMeteoros>Psi Ursa Mayoridas</lluviaMeteoros>
            <lluviaMeteoros>Ursa Mayoridas de octubre</lluviaMeteoros>
        </objetos>
        <colindantes>Bootes, Camelopardalis, Canes Venatici, Draco, Leo, Leo Minor, Lynx</colindantes>
        <observacion>
            <hemisferio>Norte</hemisferio>
            <mes>Abril</mes>
            <hora>21:00:00</hora>
        </observacion>
    </constelacion>
</mapaEstelar>
