=== DavidelPrado/2021_LMGSI_DPL/ud04/Pruebas/modelo.xsd
<?xml version="1.0"?>
<!--
Autor: David del Prado Losada
Fecha: 11/02/2021
Descripcion: ValidaciÃ³n de elementos simples.
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="modelo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                            <xs:maxInclusive value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ciclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="DAW"/>
                            <xs:enumeration value="ASIR"/>
                            <xs:enumeration value="DAM"/>
                            <xs:enumeration value="SMR"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="nombreCiclo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="3"/>
                            <xs:maxLength value="100"/>
                            <xs:pattern value="([A-Z])*"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigoPostal">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{5}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="comentario">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:whiteSpace value="collapse"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="temperatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:totalDigits value="5"/>
                            <xs:fractionDigits value="2"/>
                            <xs:minInclusive value="-50"/>
                            <xs:maxInclusive value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigoAsignatura">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="BD|LMSGI|PROG|EDD|SINF"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DavidelPrado/2021_LMGSI_DPL/ud04/Pruebas/modelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<modelo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='modelo.xsd'>
    <curso>1</curso>
    <ciclo>DAW</ciclo>
    <nombreCiclo>Desarrollo</nombreCiclo>
    <codigoPostal>47689</codigoPostal>
    <comentario>Este    ciclo   tiene   una     inserci√≥n   laboral     de  100%</comentario>
    <temperatura>24.5</temperatura>
    <codigoAsignatura>BD</codigoAsignatura>
</modelo>
