=== DavidelPrado/2021_LMGSI_DPL/ud04/03-2.dtd
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha EMPTY>
<!ELEMENT hechosHistoricos (descripcion, fecha)>
<!ELEMENT hechos (hechosHistoricos*)>
<!ATTLIST fecha dia CDATA #REQUIRED>
<!ATTLIST fecha mes CDATA #REQUIRED>
<!ATTLIST fecha anyo CDATA #REQUIRED>

=== DavidelPrado/2021_LMGSI_DPL/ud04/03-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hechos SYSTEM '03-2.dtd'>

<hechos>
    <hechosHistoricos>
        <descripcion>Se funda Youtube</descripcion>
        <fecha dia="15" mes="2" anyo="2005"/>
    </hechosHistoricos>
    <hechosHistoricos>
        <descripcion>Se funda Google</descripcion>
        <fecha dia="4" mes="9" anyo="1998"/>
    </hechosHistoricos>
    <hechosHistoricos>
        <descripcion>Se funda Facebook</descripcion>
        <fecha dia="4" mes="2" anyo="2004"/>
    </hechosHistoricos>
</hechos>
