=== DavidelPrado/2021_LMGSI_DPL/ud04/03.dtd
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>
<!ELEMENT fecha (dia, mes, anyo)>
<!ELEMENT hechosHistoricos (descripcion, fecha)>
<!ELEMENT hechos (hechosHistoricos*)>

=== DavidelPrado/2021_LMGSI_DPL/ud04/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hechos SYSTEM '03.dtd'>

<hechos>
    <hechosHistoricos>
        <descripcion>Se funda Youtube</descripcion>
        <fecha>
            <dia>15</dia>
            <mes>2</mes>
            <anyo>2005</anyo>
        </fecha>
    </hechosHistoricos>
    <hechosHistoricos>
        <descripcion>Se funda Google</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>9</mes>
            <anyo>1998</anyo>
        </fecha>
    </hechosHistoricos>
    <hechosHistoricos>
        <descripcion>Se funda Facebook</descripcion>
        <fecha>
            <dia>4</dia>
            <mes>2</mes>
            <anyo>2004</anyo>
        </fecha>
    </hechosHistoricos>
</hechos>
